Repository felix-elugbaju/Group_B_VirtualEscapeRoom, pull requests merged in 2020-12, with the labels that each got.

#14 Added new functionalities to main and some other functions
  arghandling.c
  arghandling.h
  execution.c
  main.c
  object.c
Labels: enhancement

#27 Added minor improvements to main and puzzle1 and doxygen comments to most functions.
  arghandling.c
  arghandling.h
  execution.c
  helper.h
  main.c
  object.c
  parsenexec.h
  puzzle.c
  puzzle.h
  readme.md
Labels: enhancement

#35 Add makefile and restructure directories as per Demo 1
  Makefile
  build/arghandling.o
  build/execution.o
  build/helper.o
  build/main.o
  build/object.o
  build/parsenexec.o
  include/arghandling.h
  include/execution.h
  include/helper.h
  include/object.h
  include/parsenexec.h
  include/puzzle.h
  puzzle.c
  src/arghandling.c
  src/execution.c
  src/helper.c
  src/main.c
  src/object.c
  src/parsenexec.c
  src/puzzle.c
Labels: documentation, enhancement

#31 New object type <hint> and more intuitive names for keys, doors, and puzzles
  Makefile
  build/arghandling.o
  build/execution.o
  build/helper.o
  build/main.o
  build/object.o
  build/parsenexec.o
  include/arghandling.h
  include/execution.h
  include/helper.h
  include/object.h
  include/parsenexec.h
  include/puzzle.h
  object.c
  puzzle.c
  readme.md
  src/arghandling.c
  src/execution.c
  src/helper.c
  src/main.c
  src/object.c
  src/parsenexec.c
  src/puzzle.c
Labels: documentation

#36 Adding updated README.md file to development branch
  README.md
  build/arghandling.o
  build/execution.o
  build/helper.o
  build/main.o
  build/object.o
  build/parsenexec.o
  include/object.h
  src/execution.c
  src/object.c
  src/parsenexec.c
  src/puzzle.c
Labels: documentation

#39 Added piano_puzzle in puzzle.c/puzzle.h. Updated helper.c to feature …
  include/helper.h
  include/object.h
  include/puzzle.h
  src/execution.c
  src/helper.c
  src/object.c
  src/puzzle.c
Labels: enhancement

#42 Updated puzzles with hint and quit features; new 7th puzzle
  .gitignore
  Makefile
  README.md
  build/arghandling.o
  build/execution.o
  build/helper.o
  build/main.o
  build/object.o
  build/parsenexec.o
  include/helper.h
  include/object.h
  include/puzzle.h
  src/execution.c
  src/helper.c
  src/main.c
  src/object.c
  src/parsenexec.c
  src/puzzle.c
Labels: enhancement

#40 Adding ability to display a map. Modified execution.c/.h, as well as …
  include/execution.h
  include/object.h
  src/execution.c
  src/object.c
  src/parsenexec.c
  src/puzzle.c
Labels: enhancement

#44 Fixed compilation issues
  Makefile
  include/execution.h
  include/object.h
  include/puzzle.h
  src/execution.c
  src/object.c
  src/parsenexec.c
  src/puzzle.c
Labels: bug
